# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(828, 437)
        self.actionNuevo_audio = QAction(MainWindow)
        self.actionNuevo_audio.setObjectName(u"actionNuevo_audio")
        self.actionGuardar_resultados = QAction(MainWindow)
        self.actionGuardar_resultados.setObjectName(u"actionGuardar_resultados")
        self.new_project = QAction(MainWindow)
        self.new_project.setObjectName(u"new_project")
        self.load_audio = QAction(MainWindow)
        self.load_audio.setObjectName(u"load_audio")
        self.load_project = QAction(MainWindow)
        self.load_project.setObjectName(u"load_project")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(-4, -1, 841, 411))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_result = QLabel(self.tab)
        self.label_result.setObjectName(u"label_result")
        self.label_result.setEnabled(True)
        self.label_result.setGeometry(QRect(370, 10, 381, 16))
        font = QFont()
        font.setPointSize(12)
        self.label_result.setFont(font)
        self.audio_name = QLabel(self.tab)
        self.audio_name.setObjectName(u"audio_name")
        self.audio_name.setEnabled(True)
        self.audio_name.setGeometry(QRect(10, 10, 381, 16))
        self.audio_name.setFont(font)
        self.start_text = QLabel(self.tab)
        self.start_text.setObjectName(u"start_text")
        self.start_text.setGeometry(QRect(130, 150, 571, 31))
        self.start_text.setFont(font)
        self.comboBox = QComboBox(self.tab)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 110, 311, 22))
        self.detect_emotions = QPushButton(self.tab)
        self.detect_emotions.setObjectName(u"detect_emotions")
        self.detect_emotions.setGeometry(QRect(10, 190, 311, 41))
        font1 = QFont()
        font1.setPointSize(10)
        self.detect_emotions.setFont(font1)
        self.label_1_speaker = QLabel(self.tab)
        self.label_1_speaker.setObjectName(u"label_1_speaker")
        self.label_1_speaker.setGeometry(QRect(10, 60, 231, 16))
        self.label_1_speaker.setFont(font)
        self.label_result_2 = QLabel(self.tab)
        self.label_result_2.setObjectName(u"label_result_2")
        self.label_result_2.setGeometry(QRect(370, 30, 241, 16))
        self.label_result_2.setFont(font1)
        self.label_2_speaker = QLabel(self.tab)
        self.label_2_speaker.setObjectName(u"label_2_speaker")
        self.label_2_speaker.setGeometry(QRect(10, 80, 391, 16))
        self.label_2_speaker.setFont(font1)
        self.textEdit = QTextEdit(self.tab)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(370, 60, 451, 301))
        self.textEdit.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.textEdit.setReadOnly(True)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label = QLabel(self.tab_3)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 90, 261, 16))
        self.label.setFont(font)
        self.save_project_name = QLineEdit(self.tab_3)
        self.save_project_name.setObjectName(u"save_project_name")
        self.save_project_name.setGeometry(QRect(20, 120, 251, 31))
        self.save_project_btn = QPushButton(self.tab_3)
        self.save_project_btn.setObjectName(u"save_project_btn")
        self.save_project_btn.setGeometry(QRect(20, 170, 251, 41))
        self.save_project_btn.setFont(font1)
        self.label_3 = QLabel(self.tab_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(440, 10, 181, 21))
        self.label_3.setFont(font)
        self.saved_projects_list = QListView(self.tab_3)
        self.saved_projects_list.setObjectName(u"saved_projects_list")
        self.saved_projects_list.setGeometry(QRect(440, 50, 361, 281))
        self.saved_projects_list.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.saved_projects_list.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.load_project_list = QListView(self.tab_2)
        self.load_project_list.setObjectName(u"load_project_list")
        self.load_project_list.setGeometry(QRect(30, 40, 361, 281))
        self.load_project_list.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.load_project_list.setSelectionMode(QAbstractItemView.SingleSelection)
        self.label_4 = QLabel(self.tab_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 10, 361, 21))
        self.label_4.setFont(font)
        self.load_project_btn = QPushButton(self.tab_2)
        self.load_project_btn.setObjectName(u"load_project_btn")
        self.load_project_btn.setGeometry(QRect(490, 130, 241, 41))
        self.load_project_btn.setFont(font1)
        self.delete_project_btn = QPushButton(self.tab_2)
        self.delete_project_btn.setObjectName(u"delete_project_btn")
        self.delete_project_btn.setGeometry(QRect(490, 180, 241, 41))
        self.delete_project_btn.setFont(font1)
        self.load_project_input = QLineEdit(self.tab_2)
        self.load_project_input.setObjectName(u"load_project_input")
        self.load_project_input.setGeometry(QRect(30, 330, 361, 31))
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QRect(0, 0, 828, 21))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.load_audio)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNuevo_audio.setText(QCoreApplication.translate("MainWindow", u"Nuevo audio", None))
        self.actionGuardar_resultados.setText(QCoreApplication.translate("MainWindow", u"Guardar resultados", None))
        self.new_project.setText(QCoreApplication.translate("MainWindow", u"Cargar audio", None))
        self.load_audio.setText(QCoreApplication.translate("MainWindow", u"Cargar audio", None))
        self.load_project.setText(QCoreApplication.translate("MainWindow", u"Cargar resultados", None))
        self.label_result.setText(QCoreApplication.translate("MainWindow", u"Resultados obtenidos del an\u00e1lisis", None))
        self.audio_name.setText(QCoreApplication.translate("MainWindow", u"Analizando el audio: audio", None))
        self.start_text.setText(QCoreApplication.translate("MainWindow", u"Selecciona un nuevo audio o carga uno previamente analizado para comenzar", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Hablante 1", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Hablante 2", None))

        self.detect_emotions.setText(QCoreApplication.translate("MainWindow", u"Detectar emociones", None))
        self.label_1_speaker.setText(QCoreApplication.translate("MainWindow", u"Selecciona el hablante a analizar", None))
        self.label_result_2.setText(QCoreApplication.translate("MainWindow", u" (separados por segmentos de tiempo):", None))
        self.label_2_speaker.setText(QCoreApplication.translate("MainWindow", u"(1 si habla primero en el audio o 2 en caso contrario):", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Nuevo an\u00e1lisis", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Escribe el nombre de este proyecto:", None))
        self.save_project_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Ej.: Proyecto 1", None))
        self.save_project_btn.setText(QCoreApplication.translate("MainWindow", u"Guardar proyecto", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Proyectos ya guardados", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Guardar resultados", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Selecciona el proyecto que deseas cargar", None))
        self.load_project_btn.setText(QCoreApplication.translate("MainWindow", u"Cargar proyecto", None))
        self.delete_project_btn.setText(QCoreApplication.translate("MainWindow", u"Eliminar proyecto", None))
        self.load_project_input.setPlaceholderText(QCoreApplication.translate("MainWindow", u"O simplemente escribe el nombre del proyecto aqu\u00ed", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Proyectos", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
    # retranslateUi

